const nodemailer = require('nodemailer');
const express = require('express');
const cors = require('cors');
const app = express();
const port = 3700;
app.use(cors());
app.use(express.json());
let transporter = nodemailer.createTransport({
    service: 'gmail',
    auth:{
        user:'pallav3198@gmail.com',
        pass:'nokiaasha230'
    }
});
// contact us page
app.post('/msgEmail',(req,res)=>{
    console.log(req.body);
    res.send('Message Received!');
    let mailOptions = {
            from: 'pallav3198@gmail.com',
            to:`${req.body.email}`,
            subject:'Message Received!',
            html:`
            <h3> Hi! ${req.body.name}</h3>
            <p>Thankyou for visiting our website.
            We appriciate your valuable comments.
            <h5> We will get back to you shortly </h5>
            <i> Please donot reply to this autogenerated mail</i>
            <br/>
            Thanks & Regards
            <br/>
            <strong> Team MTX Shoppe </strong>
            </p>
            `
        };
        transporter.sendMail(mailOptions,(err,info)=>{
            if(err){
                console.log(err);
            }
            else{
                console.log('Email Sent!'+ info.response);
            }      
        })
})
//on creation of new account
app.post('/newaccountMail',(req,res)=>{
    console.log(req.body);
    res.send('Message Received!');
    let mailOptions = {
            from: 'pallav3198@gmail.com',
            to:`${req.body.email}`,
            subject:`Welcome To MTX Shoppe`,
            html:`
            <h3> Hi! ${req.body.username}</h3>
            <p>Thankyou for registering on our website.
            Dont stop shopping with us.
            <h5> Please Note your Unique UserID </h5>
            <p> This may be used for future references </p>
            <h4 style="color:blue">+91A7678-${req.body.id}</h4>
            <i> Please donot reply to this autogenerated mail</i>
            <br/>
            Thanks & Regards
            <br/>
            <strong> Team MTX Shoppe </strong>
            </p>
            `
        };
        transporter.sendMail(mailOptions,(err,info)=>{
            if(err){
                console.log(err);
            }
            else{
                console.log('Email Sent!'+ info.response);
            }      
        })
})

// during checkout after shopping
app.post('/checkoutMail',(req,res)=>{
    console.log(req.body);
    res.send('Message Received!');
    let mailOptions = {
            from: 'pallav3198@gmail.com',
            to:`${req.body.email}`,
            subject:`Thanks for shopping with us!`,
            html:`
            <h3> Hi! ${req.body.name}</h3>
            <p>Thankyou for shopping  on our website.
            <h5> Please Note your Unique Order ID </h5>
            <p> This may be used for future references </p>
            <h4 style="color:blue">+91A7678-${req.body.email}</h4>
            <strong> For more information, contact: <span style="color:blue">+917827424113</span></strong>
            <i> Please donot reply to this autogenerated mail</i>
            <br/>
            Thanks & Regards
            <br/>
            <strong> Team MTX Shoppe </strong>
            </p>
            `
        };
        transporter.sendMail(mailOptions,(err,info)=>{
            if(err){
                console.log(err);
            }
            else{
                console.log('Email Sent!'+ info.response);
            }      
        })
})


// reset password
app.post('/resetPassword',(req,res)=>{
    console.log(req.body);
    res.send(req.body);
    let mailOptions = {
            from: 'pallav3198@gmail.com',
            to:`${req.body.email}`,
            subject:`Reset Password | MTX Shoppe`,
            html:`
            <h3>Hi! User</h3>
            <p> 
            We have received reset password request for this email.
            Please click on the below link to reset your password.
            </p>
            <h6>
        <h3>
            <a href="http://localhost:4200/reset" taget="_blank">
              http://localhost:4200/reset
            </a>
        </h3>
            </h6>
            <strong> For more information, contact: <span style="color:blue">+917827424113</span></strong>
            <i> Please donot reply to this autogenerated mail</i>
            <br/>
            Thanks & Regards
            <br/>
            <strong> Team MTX Shoppe </strong>
            </p>
            `
        };
        transporter.sendMail(mailOptions,(err,info)=>{
            if(err){
                console.log(err);
            }
            else{
                console.log('Email Sent!'+ info.response);
            }      
        })
})




app.listen(port);
